### PR TITLE
Email confirmations

### PR DESCRIPTION
**Pull request by nries1**
Changes this PR:
 - Sends an email confirmation whenever a new order is posted

Acceptance Criteria:
1) Pull this branch
2) Run the app
3) Delete your cookie
4) Refresh the page
5) Log in as yourself
6) go to /checkout
7) Complete each bread crumb START AT BILLING
8) Click confirm order
9) See that an email is sent to you.

### CODE REVIEW

**Review by ShelOrock — COMMENTED** [review]
I'm unable to submit the order at checkout. In redux it seems the cart is an array where i was under the assumption the cart is an object?

Also all the information I'm adding to the cart is getting dumped throughout the checkout. Definitely another result of the cart becoming an array instead of an object. Seeing the use of typescript rn 😩😩😩

**Comment by nries1** [comment]
> I'm unable to submit the order at checkout. In redux it seems the cart is an array where i was under the assumption the cart is an object?
> 
> Also all the information I'm adding to the cart is getting dumped throughout the checkout. Definitely another result of the cart becoming an array instead of an object. Seeing the use of typescript rn 😩😩😩

Ok that probably happened on merge. Let me see if i can fix that in this branch. Yea @ShelOrock The change came from the second commit. "Merge branch dev of..." The means that the cart functionality on dev is likely not working rn. I won't have time to look into this today unfortunately.

**Comment by wulalasuperdope** [comment]
> I'm unable to submit the order at checkout. In redux it seems the cart is an array where i was under the assumption the cart is an object?
> 
> Also all the information I'm adding to the cart is getting dumped throughout the checkout. Definitely another result of the cart becoming an array instead of an object. Seeing the use of typescript rn 😩😩😩

Early I set the state of Cart to be an array, since a user's cart can include more than one item (each item is an object for sure). I think the conflict is setCart thunk and api get Cart item route. I can talk this evening if you want to discuss it.

**Comment by ShelOrock** [comment]
Hmm... I was working from the dev branch when i was creating the checkout and the cart was still an object. The cart should no longer have billing information (and possibly shipping info) when I finish integrating stripe, but the cart will still have to have a userId that shouldn't be iterated over. I think the solution is going back to object notation and having a key called products with a value of an array that can be iterated over.

**Comment by wulalasuperdope** [comment]
> Hmm... I was working from the dev branch when i was creating the checkout and the cart was still an object. The cart should no longer have billing information (and possibly shipping info) when I finish integrating stripe, but the cart will still have to have a userId that shouldn't be iterated over. I think the solution is going back to object notation and having a key called products with a value of an array that can be iterated over.

OK, sounds good to me.

**Review by wulalasuperdope — APPROVED** [review]
YEAHHHH

**Pull request merged**
