### PR TITLE
Checkout

### PR DESCRIPTION
**Pull request by ShelOrock**
Acceptance Criteria:

1. run the app.
2. navigate to localhost:3000/checkout.
3. Click on Billing breadcrumb.
4. Fill in forms.
5. Attempt to checkout.
6. Help me figure out why the order post request is failing (may be because cart is still unfinished)
7. Checkout all the changes and let me know any concerns.

TODO: Render users billing and shipping registered to their name (if theres time. not a priority). Render Receipt of order.

### CODE REVIEW

**Review by nries1 — COMMENTED** [review]
@ShelOrock . Wow. You were not lying. This is a big PR.

It looks to me like the error that you're getting is due to the deleteCart thunk in CartThunks.js

It calls delete on the route: /api/users/${userId}/cart

but the route in api/users is listening at api/users/:userId/cart/:cartId

I'm guessing it doesn't like the undefined cart id. But without actually having a cart, this is a pretty low impact error. I see that the order is being created, which is great. The only thing I would add to this, other than checking on the error you mentioned, would be to add a row to the order details table when an order is created.

**Comment by ShelOrock** [comment]
Oh thank you! i'll check that out. The error I remember in the console was the post request on the order, but i'm guessing because i promise chained thunks (which I don't understand I thought thunks were supposed to take care of this for us but anyway...) and the delete worked it threw the error on the original thunk?

**Review by wulalasuperdope — DISMISSED** [review]
Great job!

**Review by nries1 — APPROVED** [review]
Re approving this per your comment in Slack.

**Pull request merged**
